---
title: "Analysis"
author: "John Clements_Jingjing Li"
date: "7/1/2021"
output: html_document
  toc: TRUE
---
# Introduction  

```{r}
library (readr)
library(dplyr)
library(ggplot2)
library(tidyr)
```

# Data manipulation  
```{r, message=FALSE}
bikeday <- read_csv("../Bike-Sharing-Dataset/day.csv")
bikehour <- read_csv("../Bike-Sharing-Dataset/hour.csv")
bikeday1 <- filter(bikeday,  weekday==1)
bikehour1 <- filter(bikehour,  weekday==1)
set.seed(10)
train_day1 <- sample(1:nrow(bikeday1),size=nrow(bikeday1)*0.7)
test_day1 <- setdiff(1:nrow(bikeday1), train_day1)
bikedayTrain1 <- bikeday1[train_day1, ]
bikedayTest1 <- bikeday1[test_day1, ]
train_hour1 <- sample(1:nrow(bikehour1),size=nrow(bikehour1)*0.7)
test_hour1 <- setdiff(1:nrow(bikehour1), train_hour1)
bikehourTrain1 <- bikehour1[train_hour1, ]
bikehourTest1 <- bikehour1[test_hour1, ]
```
# Summarization  
```{r}
#check effect of season on temperature, humidity and windspeed
bikedayTrain1 %>% group_by(yr,season) %>% summarise(avgtemp = mean (temp), sdtemp = sd (temp), avghum = mean(hum), sdhum = sd (hum), avgwindspd= mean(windspeed),sdwindspd=sd(windspeed) )

#compare weather situation of two different years
yr_weather<- table(bikedayTrain1$yr, bikedayTrain1$weathersit)

# compare weather situation of different seasons
season_weather <- table(bikedayTrain1$season, bikedayTrain1$weathersit)

#observe on distribution of total bike renter counts
g1<- ggplot (bikedayTrain1, aes(x=cnt))
g1 + geom_histogram() + xlab("total bike renter number") + ggtitle("Distribution of total bike renter counts")

#Effect of temperature on total bike renter number
g2 <- ggplot(bikedayTrain1, aes(x=temp, y=cnt))
g2+ geom_point()+ xlab("Normalized temperature") + ylab("Total bike renter number") + 
  ggtitle("Effect of temperature on total bike renter counts")

#Effect of windspeed on total bike renter number
g3 <- ggplot(bikedayTrain1, aes(x=windspeed, y=cnt))
g3+geom_point()+ xlab("Normalized windspeed") + 
  ggtitle("Effect of windspeed on total bike renter counts") + ylab("Total bike renter number")

#Effect of season on total bike renter number
bikedayTrain1$season <- as.factor(bikedayTrain1$season)
g4 <- ggplot(bikedayTrain1, aes(x=season, y=cnt))
g4 + geom_boxplot() + scale_x_discrete(labels= c("Winter","Spring","Summer","Fall")) + ylab("Total bike renter number") + ggtitle("Effect of season on total bike renter counts")
```
# Modeling
## Linear model 
### 2 
```{r}
bikedayTrain1$season <- as.numeric(bikedayTrain1$season)
pairs(bikedayTrain1 )
lmfit1a <- lm(casual~temp, data=bikedayTrain1)
summary(lmfit1a)

lmfit1b <- lm(casual~ mnth, data=bikedayTrain1)
summary(lmfit1b) 

lmfit1c <- lm(casual~ windspeed , data=bikedayTrain1)
summary(lmfit1c) 

lmfit1d <- lm(casual~season , data=bikedayTrain1)
summary(lmfit1d) 

lmfit2a <- lm(casual~temp*season, data=bikedayTrain1)
summary(lmfit2a)

lmfit2b <- lm(casual~temp*windspeed, data=bikedayTrain1)
summary(lmfit2b)

lmfit2c <- lm(casual~season*windspeed, data=bikedayTrain1)
summary(lmfit2c)

lmfit3a <- lm(casual~ temp + I(temp^2), data=bikedayTrain1)
summary(lmfit3a) 

lmfit3b <- lm(casual~ windspeed + I(windspeed ^2), data=bikedayTrain1)
summary(lmfit3b)
lmfit3c <- lm(casual~ season + I(season^2), data=bikedayTrain1)
summary(lmfit3c) 

lmfit4a <- lm(casual~temp*windspeed, data=bikedayTrain1)
summary(lmfit4a)

lmfit4b <- lm(casual~temp*season, data=bikedayTrain1)
summary(lmfit4b)

lmfit5a <- lm(casual~temp*windspeed*season, data=bikedayTrain1)
summary(lmfit5a)

lmfit5b <- lm(casual~temp*windspeed*season + I(temp^2)+ I(windspeed^2)+ I(season^2), data=bikedayTrain1)
summary(lmfit5b)

trainFit <- function (fit) {
  model <- round(c(summary(fit)$adj.r.squared, AIC(fit), 
                   MuMIn::AICc(fit), BIC(fit)), 3)
  name <- c("adj.r.sqr", "AIC","AICc", "BIC")
  df_stat <- data.frame(name, model)
  df_stat2 <- spread(df_stat, name, model)
}
stat1a <- trainFit(lmfit1a)
stat1b <- trainFit(lmfit1b)
stat1c <- trainFit(lmfit1c)
stat1d <- trainFit(lmfit1c)
  
stat2a <- trainFit(lmfit2a)
stat2b <- trainFit(lmfit2b)
stat2c <- trainFit(lmfit2c)

stat3a <- trainFit(lmfit3a)
stat3b <- trainFit(lmfit3b)
stat3c <- trainFit(lmfit3c)
    
stat4a <- trainFit(lmfit4a)        
stat4b <- trainFit(lmfit4b) 

stat5a<- trainFit(lmfit5a)
stat5b<- trainFit(lmfit5a)

stat_sum <- rbind(stat1a,stat1b,stat1c,stat1d,stat2a,stat2b,stat2c,stat3a,stat3b,stat3c,stat4a,stat4b,stat5a,stat5b)
rownames (stat_sum) <-c("lmfit1a","lmfit1b","lmfit1c","lmfit1d","lmfit2a","lmfit2b","lmfit2c", "lmfit3a","lmfit3b","lmfit3c","lmfit4a","lmfit4b","lmfit5a","lmfit5b") 
stat_sum 
```
## Ensemble tree model
### boosted tree 
```{r}
set.seed(50)
gbmGrid <- expand.grid(interaction.depth=4, n.trees = 1000,
                   shrinkage=0.1,
                   n.minobsinnode=10)
gbmFit <- train (casual ~., data=select(bikedayTrain1, -"weekday"),
                   method="gbm",
                   preProcess= c("center", "scale"),
                   trControl = trainControl(method = "cv",
                                            number=10),
                    tuneGrid=gbmGrid)
gbmFit 
```

